version: "3.8"

services:
  #nginx
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes :
      - ./www:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php     
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
     - ./www:/var/www/html:delegated
  mysql:
   platform: linux/x86_64 
   image: mysql:8
   env_file:
    - ./env/mysql.env
   ports:
    - 3306:3306
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3307:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
    - ./env/phpmyadmin.env
    ports:
      - 81:80     